### ISSUE TITLE
Error on trying to run

### ISSUE THREAD

**Issue by bphillips330** [Jayapraveen/INE-courses-downloader#10]
I have tried to run from Linux and win10.  python3.9.1
getting this

INE-courses-downloader $ python Ine.py
/home/ben/git/INE-courses-downloader/Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
Traceback (most recent call last):
  File "/home/ben/git/INE-courses-downloader/Ine.py", line 24, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Tried changing the "is" to ==  still did not work. 

On win10 I got this error

Traceback (most recent call last):
  File "C:\Users\Ben\Downloads\python\Ine.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Jayapraveen** [comment]
Fixed in the commit `1eb4279`
Install requirements as mentioned in the readme.
