### ISSUE TITLE
Issue download

### ISSUE THREAD

**Issue by bphillips330** [Jayapraveen/INE-courses-downloader#11]
every time I run script.  Site Rip just says I don't have subscription pass to access to this course for every file.  So I went to individual download of file.  Select 1080p and course number.  And I still get the can't download due to not having subscription.   I can watch the videos if I log into INE so I know I have access.  Anybody get this to work?

**Comment by dexter101010** [comment]
Same problem here : 

Warning! Until the script completes execution do not access INE website or mobile app
 as it might invalidate the session!

Cloud
Data Science
Development
IT Essentials
Networking
Cyber Security
Choose Method Of Operation:
1.Site Rip
2.Select Individual Course



Choose Preferred Video Quality
1.1080p
2.720p
2
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
2
Please enter the number corresponding to the course you would like to download
2
Traceback (most recent call last):
  File "Ine.py", line 461, in <module>
    if(course["access"]["related_passes"][0]["name"] in access_pass):
TypeError: argument of type 'NoneType' is not iterable



0. Version Control & GitHub
1. Bash Scripting for Data Scientists
2. Segmenting Traffic with VLANs & Trunks
3. Configuration Consistency with Ansible
4. Machine Learning with scikit-learn Starter Pass
5. Data Analysis with pandas Starter Pass

**Comment by Jayapraveen** [comment]
Fixed in the commit `b29c48d`.
