### ISSUE TITLE
List index out of range - unable to download

### ISSUE THREAD

**Issue by FrostMatt** [Jayapraveen/INE-courses-downloader#13]
Error when downloading, I’ve tried with a couple courses (65,89,400 and 835) but same error. Running latest version (27916ea) this morning

Total 836 courses

Choose Preferred Video Quality
1.1080p
2.720p
1
Choose Method Of Selecting Course
1.Enter url
2.Choose from the above listed course
2
Please enter the number corresponding to the course you would like to download
834

Traceback (most recent call last):
  File "Ine.py", line 470, in <module>
    if(course["access"]["related_passes"][4]["name"] in access_pass):
IndexError: list index out of range

Thank you

**Comment by Jayapraveen** [comment]
Should be fixed in (6ea35ca). Removed the hardcoded index value to resolve this issue.
