### ISSUE TITLE
List courses to download

### ISSUE THREAD

**Issue by vikdean** [Jayapraveen/INE-courses-downloader#2]
Hi,
would it be possible to implement an option to not just download a single course, but define a list of course numbers (so e.g. instead of just "100", enter "100, 102, 152, 153"?

Thanks

**Comment by Jayapraveen** [comment]
Hello @vikdean 
A similar feature is in development and will let you know when it's complete.

**Comment by Jayapraveen** [comment]
Added the feature in commit `5f249d0`.
