### ISSUE TITLE
I can't figure out how to configure the script.

### ISSUE THREAD

**Issue by DennisSergge** [Jayapraveen/INE-courses-downloader#20]
I can't figure out how to configure the script.
Just starting to learn Python.
I am ready to ask the author for help in setting up.
Thank you.

**Comment by bkwg** [comment]
By "configure the script" if you mean choosing a custom download path as described in the README, just open the script (_Ine.py_) in a text editor and modify lines 25 and 26 accordingly.

But if you mean providing your personal info and choosing the courses you want to download, you just have to run the script and follow the indications, every option is described.

**Comment by DennisSergge** [comment]
(base) 911:INE-courses-downloader Home$ python    Ine.py 
   File "Ine.py", line 444
     p.map(downloader,(all_courses[j] for j in range(i, this_session) if (False if (len(all_courses[j]["access"]["related_passes"]) == 0) else True if (course_has_access(all_courses[j])) else False) and 1 or print("Course not in subscription access pack. Skipping ..")))
                                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
(base) 911:INE-courses-downloader Home$ 

Thank you for quick response.
The fact of the matter is that I entered my credentials, but I see this. error. I don't really understand what I'm doing wrong.
Thanks for your participation and help
 
  
>Вторник, 27 апреля 2021, 18:24 +03:00 от bkwg ***@***.***>:
> 
> 
>By "configure the script" if you mean choosing a custom download path as described in the README, just open the script ( Ine.py ) in a text editor and modify lines 25 and 26 accordingly.
>But if you mean providing your personal info and choosing the courses you want to download, you just have to run the script and follow the indications, every option is described.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Denis Sergge

**Comment by DennisSergge** [comment]
i bought an annual subscription Cyber Security Pass
but I can not download any files or videos.
this causes a lot of problems.
I would be glad if your script helps in solving this problem.


  
>Вторник, 27 апреля 2021, 18:24 +03:00 от bkwg ***@***.***>:
> 
> 
>By "configure the script" if you mean choosing a custom download path as described in the README, just open the script ( Ine.py ) in a text editor and modify lines 25 and 26 accordingly.
>But if you mean providing your personal info and choosing the courses you want to download, you just have to run the script and follow the indications, every option is described.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Denis Sergge

**Comment by bkwg** [comment]
I think that you are using python 2.X.
Use python3

**Comment by DennisSergge** [comment]
You so facking good.
Thank you so much
everything is working.
How can I assign you? 
>Вторник, 27 апреля 2021, 21:32 +03:00 от bkwg ***@***.***>:
> 
> 
>I think that you are using python 2.X.
>Use python3
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Denis Sergge
