### ISSUE TITLE
Will INE ban my account?

### ISSUE THREAD

**Issue by Rejected-Peice** [Jayapraveen/INE-courses-downloader#25]
Pluralsight, and IT Pro TV bans account if they see high activity.
I am assuming you have did the site-rip (I think thats how u got the size that its 1.8TB), can u confirm that they did not ban your account?

**Comment by Jayapraveen** [comment]
@Rejected-Peice, The estimation was got through dry running the script without the downloader. I suggest on the safer side its better to use other downloading options and select only the courses that are required the most, as siterip will spawn multiple threads to accomplish downloading,
