### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/INE-courses-downloader#3]
Hi bro, 

It seems there is a problem with authentication. In browser it works with the same username and pass that i am using 
in command prompt. But in command prompt i get this : 

Enter your Username: blabla@yahoo.fr
Enter your Password:

Username or password is incorrect

Choose from the following options:
1.Relogin
2.Exit

And if i choose 1 , it exit.

**Comment by Jayapraveen** [comment]
Whenever changes are made to their authentication mechanism, the downloader has to be updated to reflect the changes. As of with commit `1eb4279`, the issue seems to be fixed. Raise issues if any in the future.
