### ISSUE TITLE
You do not have the subscription/pass to access to this course

### ISSUE THREAD

**Issue by pwnedDesal** [Jayapraveen/INE-courses-downloader#35]
I have subscription but I got this error

**Comment by Lomar5115** [comment]
> 


Have you found any solution ??

**Comment by dlmart1972** [comment]
try this i just posted

thread linked below

https://github.com/Jayapraveen/INE-courses-downloader/issues/37

**Comment by pwnedDesal** [comment]
Does not work @dlmart1972
