### ISSUE TITLE
Script isn't working anymore

### ISSUE THREAD

**Issue by Lomar5115** [Jayapraveen/INE-courses-downloader#36]
I tried to run the script many times everytime it shows another error, Can you check if you must change something likr modules or logging autoinfection code.

With thanks

**Comment by dlmart1972** [comment]
script works fine ;D 

I've even added token refresh to it

**Comment by Lomar5115** [comment]
> script works fine ;D
> 
> I've even added token refresh to it

Can you please guide me? if you've telegram dm me please. I have an exam in the middle of the month & I need to download the material for Offline studying

**Comment by dlmart1972** [comment]
this is probably your issue

edit the login() 

https://github.com/Jayapraveen/INE-courses-downloader/issues/34
