### ISSUE TITLE
Can't get access it says "NameError: name 'access_token' is not defined"

### ISSUE THREAD

**Issue by Extremalzhez** [Jayapraveen/INE-courses-downloader#42]
Hi, could you help me with your script please, i've got an error after trying to run the script, credentials were right but i've got an error:

Warning! Until the script completes execution do not access INE website or mobile app
 as it might invalidate the session!

Traceback (most recent call last):
  File "D:\git\INE-courses-downloader\Ine.py", line 652, in <module>
    access_pass = pass_validator()
  File "D:\git\INE-courses-downloader\Ine.py", line 189, in pass_validator
    header = {"Host": host,"Origin": referer,"Authorization": access_token,"User-Agent": user_agent,"Accept": accept,"X-Requested-With": x_requested_with,"Accept-Encoding": accept_encodings,"sec-fetch-mode": sec_fetch_mode,"sec-fetch-dest": sec_fetch_dest,"Referer": referer}
NameError: name 'access_token' is not defined

**Comment by ghost** [comment]
means the pass_validator() is not working

most likely its the removed refresh_token from the json. in previous issues posted there is a fix for this.

**Comment by ghost** [comment]
https://github.com/Jayapraveen/INE-courses-downloader/issues/34

**Comment by Extremalzhez** [comment]
I have changed the line:
(old) refresh_token = login_data["data"]["tokens"]["data"]["Refresh"] 
(new) refresh_token = login_data["data"]["tokens"]["data"]["Bearer"]

But it didn't work, i've done all things that you're posted in #34 


I'm newbie in python, could you please tell me which line i need to fix, i need this script to be working

[Ine2.txt](https://github.com/Jayapraveen/INE-courses-downloader/files/9293395/Ine2.txt)

**Comment by Extremalzhez** [comment]
the failure in line 187, it says access_token is not defined, so what should i do?

**Comment by Extremalzhez** [comment]
Ok, i solved the problem, thank you!

**Comment by ghost** [comment]
hope info given helped ;D
