### ISSUE TITLE
[Question] Iframe slides download ?

### ISSUE THREAD

**Issue by shadofren** [Jayapraveen/INE-courses-downloader#6]
Do you know how to rip the slides in html format (created by iSpring) embedded in iframe as well? 

The slides has Next button and lazily load the contents. Do you have any idea on how to download these?

**Comment by amrayoub** [comment]
Did you manage to run the script?

**Comment by Emusta** [comment]
Great updates so far on the script and its working now, it would be great to add the ability to download the slides of the course.

**Comment by akanii** [comment]
Amazing feature thanks for enhancement plz try to solve makedir function error

**Comment by Jayapraveen** [comment]
A community member by the name "Pi" generously volunteered and wrote the feature for it. It has been added in the commit (8828d1b). Thankyou to "Pi". If you have any issues with that feature, please comment it here. If no concern is raised I will close this issue on 9/6/2021
