### ISSUE TITLE
Script problem.

### ISSUE THREAD

**Issue by molitona** [Jayapraveen/INE-courses-downloader#9]
Traceback (most recent call last):
  File "Ine.py", line 458, in <module>
    downloader(course)
  File "Ine.py", line 341, in downloader
    download_video(out[1],out[0])
  File "Ine.py", line 258, in download_video
    video = requests.get(url, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '0': No schema supplied. Perhaps you meant http://0?

**Comment by jayaram-yalla** [comment]
i see the same error. is this fixed ?

**Comment by jayaram-yalla** [comment]
Choose Preferred Video Quality
1.1080p
2.720p
1
Warning! This is a high compute and throughput functionality and needs
lots and lots of compute time and storage space
Enter "I agree" to acknowledge and proceed!
I agree

Initializing for Site dump

  0%|                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
Courses to be downloaded this batch: 0  to  2
Course not in subscription access pack. Skipping ..
Course not in subscription access pack. Skipping ..
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:

Course batch successfully completed downloading.. Starting Next batch..

  0%|                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
Courses to be downloaded this batch: 2  to  4
Course not in subscription access pack. Skipping ..
Course not in subscription access pack. Skipping ..
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:

Course batch successfully completed downloading.. Starting Next batch..


  0%|                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
Courses to be downloaded this batch: 4  to  6
Course not in subscription access pack. Skipping ..
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py:261: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if video.status_code is 200:
Downloading course file: INE_Deploy-Windows-Course-Files.zip: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.88s/it]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\download\INE-courses-downloader-master\INE-courses-downloader-master\Ine.py", line 313, in downloader
    course_preview = course_preview_meta_getter(preview_id,quality)
NameError: name 'quality' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Ine.py", line 423, in <module>
    p.map(downloader,(all_courses[j] for j in range(i, this_session) if (False if (len(all_courses[j]["access"]["related_passes"]) == 0) else True if (all_courses[j]["access"]["related_passes"][0]["name"] in access_pass) else False) and 1 or print("Course not in subscription access pack. Skipping ..")))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
NameError: name 'quality' is not defined
  0%|                                                                                                                                                                       | 0/2 [00:06<?, ?it/s]
  0%|                                                                                                                                                                       | 0/2 [00:05<?, ?it/s]
  0%|                                                                                                                                                                       | 0/2 [00:04<?, ?it/s]

D:\download\INE-courses-downloader-master\INE-courses-downloader-master>

**Comment by Jayapraveen** [comment]
Try the version with the commit `35542ff`.
